language: ruby
rvm:
 - 2.2.6
 - 2.3.3
 - 2.4.1
 - jruby-9.1.5.0
 - jruby-1.7.26
bundler_args: --without production
script:
  - bundle exec rspec spec
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
addons:
  apt:
    packages:
      - haveged
